version: '3'

services: 

  security-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "demo"
      POSTGRES_DB: "personalerp-security-db"
    ports:
      - "5401:5432"
    volumes:
      - ./data/security-db:/var/lib/postgresql/data 
    networks:
      - personalerp-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "orlando.burli@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "JGSaFb2YbmhsN4Yb"
    ports:
      - "5400:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - security-db
    networks:
      - personalerp-compose-network

networks: 
  personalerp-compose-network:
    driver: bridge