apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: personalerp-cluster-stg
  region: sa-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 3
  - name: ng-2
    instanceType: t2.micro
    desiredCapacity: 5
